/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String[] args) {
    	String desiredSfoa = "Urban Ladder";
        String sofaLocator = "//b[contains(text(),'"+desiredSfoa+"')]";
    	System.out.println(sofaLocator);
        
    }
}
