/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.testng.annotations.Test;

import io.restassured.builder.RequestSpecBuilder;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import static io.restassured.RestAssured.given;
import static org.testng.Assert.assertTrue;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	RequestSpecBuilder builder = new RequestSpecBuilder();
		RequestSpecification requestspec;


		builder.setBaseUri("http://okmry52647dns.eastus.cloudapp.azure.com:8089");
		builder.setBasePath("/rest/api/wishlist/240");
		builder.setAccept("application/json");
		builder.setContentType("application/json");

		requestspec = builder.build();
		System.out.println("BUILD successfull");
		Response response = given(requestspec).when().get().then().extract().response();
		System.out.println(response.getStatusCode());
    }
}
